
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reviews_app_development

test:
  <<: *default
  database: reviews_app_test

production:
  <<: *default
  database: reviews_app_production
  username: reviews_app
  password: <%= ENV['REVIEWS_APP_DATABASE_PASSWORD'] %>
